# Generated by Django 3.0.6 on 2020-08-02 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0002_exam_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSectionContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_container_title', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Exam')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='ExamSectionDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.TextField()),
                ('section_html', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('exam_section_container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_details.ExamSectionContainer')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
