# Generated by Django 3.0.6 on 2020-06-04 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
        ('exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0001_initial'),
        ('chapters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuestionProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correctly_solved', models.BooleanField(default=False)),
                ('time_taken_to_solve', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chapters.Chapter')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Exam')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Question')),
                ('question_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.QuestionChoice')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.Subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'question')},
            },
        ),
        migrations.CreateModel(
            name='UserQuestionProgressLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correctly_solved', models.BooleanField(default=False)),
                ('time_taken_to_solve', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('question_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.QuestionChoice')),
                ('user_question_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_question.UserQuestionProgress')),
            ],
        ),
    ]
