# Generated by Django 3.0.6 on 2020-05-23 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailsignup', '0002_auto_20200523_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
