# Generated by Django 3.0.6 on 2020-08-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailsignup', '0003_auto_20200523_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_superteacher_admin',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
